server:
  port: 3333
  
spring:  application:    name: API-GATEWAY
  
zuul:  prefix: /ms
  routes:
    greet:      path: /api1/**
      service-id: GREET-SERVICE    welcome: 
       path: /api2/**
       service-id: WELCOME-SERVICE
       url: http://localhost:1111/welcome
       
       
      